kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-admins
subjects:
  - kind: User
    name: michael@johnson.computer
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
